### ISSUE TITLE
mintCapacityCreditsNFT on contract client throws gas estimation error

### ISSUE THREAD

**Issue by anshss** [LIT-Protocol/Issues-and-Reports#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK version

6.0.3

### Lit Network

habanero

### Description of the bug/issue

<img width="1069" alt="Screenshot 2024-07-10 at 9 42 55 AM" src="https://github.com/LIT-Protocol/Issues-and-Reports/assets/73519543/61bf6655-cb4f-4aad-ab48-8df5bffa9c2f">

### Severity of the bug

medium

### Steps To Reproduce

While executing the following code on browser

```
export async function getCapacityCredits() {
    const provider = new ethers.providers.JsonRpcProvider("https://chain-rpc.litprotocol.com/replica-http")

    const walletWithCapacityCredit = new Wallet(
        "<private key>",
        provider
    );

    let contractClient = new LitContracts({
        signer: walletWithCapacityCredit,
        network: "habanero",
    });

    await contractClient.connect();

    console.log("connected");

    const { capacityTokenIdStr } = await contractClient.mintCapacityCreditsNFT({
        requestsPerKilosecond: 80,
        requestsPerDay: 14400,
        requestsPerSecond: 10,
        daysUntilUTCMidnightExpiration: 2,
    });

    console.log("minted");
}
```

**Comment by awisniew207** [comment]
Hello!<br><br>This issue is happening because the `Wallet` you are creating does not have any Lit token! Because you are using a wallet without any token, `ethers` will warn you about the transaction failing due to no tokens for gas fees. If you go to the faucet ([https://faucet.litprotocol.com/](https://faucet.litprotocol.com/)) and enter the public wallet address corresponding to the private address in your `walletWithCapacityCredit` variable, it will allow you to successfully mint a capacity credits NFT! <br><br>If you run into any issues during this process, please let me know!

**Comment by anshss** [comment]
Hey,
I had funds in my wallet but maybe they were too low. I claimed again from
the faucet and this worked for me.

Thankyou,
Ansh
